return {
  {import = "plugins.alpha-nvim"},
  {import = "plugins.auto-session"},
  {import = "plugins.autoclose"},
  {import = "plugins.autotags"},
  {import = "plugins.ccc"},
  {import = "plugins.codewindow"},
  {import = "plugins.coloriser"},
  {import = "plugins.colorscheme"},
  {import = "plugins.comment"},
  {import = "plugins.dressing"},
  {import = "plugins.flash"},
  {import = "plugins.fzf-lua"},
  {import = "plugins.gitsigns"},
  {import = "plugins.indent-blankline"},
  {import = "plugins.lualine"},
  {import = "plugins.neoscroll"},
  {import = "plugins.smartcolumn"},
  {import = "plugins.nvim-surround"},
  {import = "plugins.nvim-tree"},
  {import = "plugins.nvim-treesitter"},
  {import = "plugins.suda"},
  {import = "plugins.telescope"},
  {import = "plugins.translate"},
  {import = "plugins.undotree"},
  {import = "plugins.vim-tmux-navigator"},
  {import = "plugins.plenary"},



  {import = "plugins.lsp.complition"},
  {import = "plugins.lsp.mason-lspconfig"},
  {import = "plugins.lsp.mason"},
  {import = "plugins.lsp.none-ls"},
  {import = "plugins.lsp.nvim-lspconfig"},
}
