return {
  {import = "plugins.alpha-nvim"},
  {import = "plugins.autoclose"},
  {import = "plugins.autotags"},
  {import = "plugins.ccc"},
  {import = "plugins.codewindow"},
  {import = "plugins.coloriser"},
  {import = "plugins.colorscheme"},
  {import = "plugins.comment"},
  {import = "plugins.dressing"},
  {import = "plugins.flash"},
  {import = "plugins.fzf-lua"},
  {import = "plugins.gitsigns"},
  {import = "plugins.indent-blankline"},
  {import = "plugins.lualine"},
  {import = "plugins.markdown-preview"},
  {import = "plugins.navigator"},
  {import = "plugins.neoscroll"},
  {import = "plugins.smartcolumn"},
  {import = "plugins.spectre"},
  {import = "plugins.nvim-surround"},
  {import = "plugins.nvim-tree"},
  {import = "plugins.nvim-treesitter"},
  {import = "plugins.nvimesweeper"},
  {import = "plugins.persistence"},
  {import = "plugins.suda"},
  {import = "plugins.translator"},
  {import = "plugins.undotree"},
  {import = "plugins.plenary"},
  {import = "plugins.zen-mode"},



  {import = "plugins.lsp.coc"},
  -- {import = "plugins.lsp.complition"},
  -- {import = "plugins.lsp.mason-lspconfig"},
  -- {import = "plugins.lsp.mason"},
  -- {import = "plugins.lsp.none-ls"},
  -- {import = "plugins.lsp.nvim-lspconfig"},
  -- {import = "plugins.lsp.nvim-lint"},
}
